### ISSUE TITLE
practica individual

### ISSUE THREAD

**Issue by ANGELGARCIASANTIAGO** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-ANGELGARCIASANTIAGO-12#1]
LUIS_ANGEL_GARCIA_SANTIAGO_1AS_24620204

**Comment by ANGELGARCIASANTIAGO** [comment]
[sistemas numericos individual18.pdf](https://github.com/user-attachments/files/16860894/sistemas.numericos.individual18.pdf)

**Comment by JordanMendoza401** [comment]
Portada 23/25
Procedimiento 25/25
Figuras ilustrativas y fotografías 24/25
Resultados y Conclusiones 23/25
Calificación de la práctica: 19

**Comment by josealfredo79** [comment]
bien hecho y revisado..
